apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/cloud-exame/hello-repo/backend:latest
        name: network-backend
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "development" 
        - name: MONGO_DB_CONNECTION_STRING
          value: "mongodb+srv://testuser:root@cluster0.wpok3i5.mongodb.net/?retryWrites=true&w=majority"
        - name: MONGO_DB_NAME
          value: "cluster0"
        - name: REDIS_URI
          value: "rediss://default:AVNS_kMKKKHMw5BQGXUmfDHJ@redis-eab5b48-student-c1eb.aivencloud.com:20452"
        - name: CORS_ORIGIN
          value: "*"
        ports:
          - name: http
            containerPort: 3000
        resources: {}
status: {}
